import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/dashboard/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main 
          style={{height: 'calc(100vh - 80px)'}} 
          className="flex flex-col items-center w-screen overflow-y-auto overflow-x-hidden relative">
          {children}
        </main>
      </body>
    </html>
  );
}
